- lib/topic_extensions.rb
- plugin.rb
Solve N+1 when in:personal filter is included in search
> FIX: eager load encrypt tables in search

- assets/javascripts/discourse/components/encrypt-enable-dropdown.js.es6
- assets/javascripts/discourse/connectors/user-preferences-account/encrypt.hbs
- assets/javascripts/discourse/connectors/user-preferences-account/encrypt.js.es6
- assets/javascripts/lib/discourse.js.es6
- assets/javascripts/lib/protocol.js.es6
- config/locales/client.en.yml
This pull request contains small, miscellaneous improvements to the controls found in user preferences.
> Miscellaneous improvements

- app/jobs/scheduled/encrypted_post_timer_evaluator.rb
Messages must be deleted in reverse order. The first post connected to the topic should be deleted as last.
> FIX: correct order to delete the message

- assets/javascripts/discourse/connectors/composer-action-after/encrypt.hbs
- assets/javascripts/discourse/initializers/hook-decrypt-post.js.es6
- assets/javascripts/discourse/widgets/encrypted-post-timer-counter.js.es6
- assets/stylesheets/common/encrypt.scss
- config/locales/client.en.yml
* move the timer to the top right corner of the post
* add a tooltip with explanation what will happen
> FIX: visual improvements for the timer

- app/controllers/encrypt_controller.rb
- assets/javascripts/discourse/connectors/user-preferences-account/encrypt.hbs
- assets/javascripts/discourse/connectors/user-preferences-account/encrypt.js.es6
- assets/javascripts/discourse/controllers/activate-encrypt.js.es6
- assets/javascripts/discourse/controllers/export-key-pair.js.es6
- assets/javascripts/discourse/templates/modal/activate-encrypt.hbs
- assets/javascripts/discourse/templates/modal/generate-paper-key.hbs
- assets/javascripts/lib/discourse.js.es6
- assets/javascripts/lib/pack.js.es6
- assets/javascripts/lib/paper_key.js.es6
- config/locales/client.en.yml
This pull request contains two individual commits which touch different parts with the sole purpose of improving the user experience.
> General user experience improvements

- assets/javascripts/discourse/connectors/composer-action-after/encrypt.js.es6
- assets/javascripts/discourse/connectors/user-preferences-account/encrypt.js.es6
- assets/javascripts/discourse/initializers/auto-enable-encrypt.js.es6
- assets/javascripts/discourse/initializers/hook-composer.js.es6
- assets/javascripts/discourse/initializers/hook-decrypt-post.js.es6
- assets/javascripts/discourse/initializers/hook-decrypt-revision.js.es6
- assets/javascripts/discourse/initializers/hook-decrypt-topic.js.es6
- assets/javascripts/discourse/initializers/hook-draft.js.es6
- assets/javascripts/discourse/initializers/hook-encrypt-upload.js.es6
- assets/javascripts/discourse/initializers/hook-gather-keys.js.es6
- assets/javascripts/discourse/initializers/hook-invite.js.es6
- assets/javascripts/discourse/initializers/hook-save.js.es6
- assets/javascripts/discourse/initializers/update-state.js.es6
- assets/javascripts/lib/discourse.js.es6
- test/javascripts/acceptance/encrypt-test.js.es6
- test/javascripts/lib/discourse-test.js.es6
Can't access Discourse.SiteSettings, so pass it in.
> FIX: errors in Ember CLI

- assets/javascripts/discourse/initializers/add-search-results.js
- assets/javascripts/discourse/initializers/decrypt-topics.js
- assets/javascripts/discourse/initializers/fetch-encrypt-keys.js
- plugin.rb
- test/javascripts/acceptance/encrypt-test.js
This commit also implements search in encrypted bookmarks and improves
existent encrypted topic search.
> FEATURE: Decrypt bookmark titles

- assets/javascripts/discourse/initializers/decrypt-posts.js
This new logical assignments are not supported by for example Tor browser.
According to documentation, `a ||= b` is equivalent to `a || (a = b) `
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment
> FIX: get rid of logical or assignments

- assets/javascripts/lib/uppy-upload-encrypt-plugin.js
See https://github.com/discourse/discourse/pull/14275
> DEV: Refactor the uppy plugin for encrypt to use new core interface

- plugin.rb
Loading private messages used to generate N+1 queries because encrypted
topic data (the encrypted topic title) and user's topic key were loaded
sequentially.
> PERF: Preload encryption keys in topic lists

- assets/javascripts/discourse/initializers/add-search-results.js
Filtering has been improved to ignore empty words and order the results
by the number of matched words in query relative to the result of the
length (i.e. closer matches will be at the top of the list).
Encrypted results that were returned by the server will be decrypted and
saved into the cache.
> FIX: Improve search in encrypted topics

- assets/javascripts/discourse/initializers/encrypt-uploads.js
- assets/javascripts/lib/uppy-upload-encrypt-plugin.js
@udan11 added review comments post-merge to
https://github.com/discourse/discourse-encrypt/pull/131,
they are being resolved in this commit
> DEV: Review fixes from previous commit

- assets/javascripts/discourse/initializers/add-search-results.js
This changes the search algorithm to select topics whose title matches
all words from the search query. It used to match topics that contained
at least one word from the search query.
> FIX: Change search to fully match the query

- assets/javascripts/discourse/controllers/generate-paper-key.js
- test/javascripts/lib/base64-test.js
- test/javascripts/lib/protocol-v0-test.js
See https://github.com/discourse/eslint-config-discourse/commit/4f7aba06c03fdd22bb26669aeb8ed4af3127c409
> DEV: Update code for eslint object-shorthand-rule

- assets/javascripts/discourse/initializers/decrypt-topics.js
The topic title from a topic page used to be replaced with the decrypted
title after it was rendered. This meant that the placeholder title
element was replaced with another element that contained the decrypted
topic title.
This was a problem because it changed the DOM structure and Ember stored
references to elements it rendered, but were replaced. More
specifically, it called `removeChild` to remove an element that did not
exist anymore, which threw an exception.
This solution gets the model object from the topic controller and
replaces its fancy_title with the decrypted title.
> FIX: Swap fancy_title with decrypted title

- assets/javascripts/discourse/initializers/encrypt-uploads.js
In core PR https://github.com/discourse/discourse/pull/15058
we are changing to use uppy by default in the composer, so
there is no need for the experimental composer uploader check.
**Do not merge before core PR.**
> DEV: Change to use uppy encrypt plugin by default

- assets/stylesheets/common/encrypt.scss
fixes hover and focus styles for these buttons
Before:
After:
> UX: minor composer button style updates

- spec/plugin_spec.rb
post_uploads will be replaced with upload references in the future.
> DEV: Do not use post_uploads relation in specs

- test/javascripts/acceptance/encrypt-test.js
This tests that drafts for encrypted new topics and replies are saved
on the server side.
> DEV: Add test to make sure that drafts are saved

- plugin.rb
Adds support for polymorphic bookmarks in the serializer extensions
and preloaders for bookmarks.
> FIX: Polymorphic bookmarks support

- test/javascripts/acceptance/encrypt-test.js
The core PR https://github.com/discourse/discourse/pull/16729
will not pass with this test, I will unskip it when we merge
the core PR.
> DEV: Skip bookmark test for now

- test/javascripts/acceptance/encrypt-test.js
Context: https://github.com/discourse/discourse/pull/16979
> DEV: Update tests for removal of reply_as_new_topic

- assets/javascripts/discourse/initializers/decrypt-posts.js
Fixes random exceptions in tests.
> FIX: Try to post process a post only if it exists

- assets/javascripts/discourse/initializers/decrypt-topics.js
- assets/javascripts/lib/discourse.js
- test/javascripts/acceptance/encrypt-test.js
See https://github.com/discourse/discourse/pull/18046 for details.
> DEV: Decrypt titles in the experimental user menu

- test/javascripts/acceptance/encrypt-test.js
The API response for `/u/:username/user-menu-private-messages` has been changed in https://github.com/discourse/discourse/pull/18390 so we need to update the fixtures in this plugin to reflect the new changes.
> DEV: Fix JS tests

- test/javascripts/acceptance/encrypt-test.js
This slight core change breaks this test
https://github.com/discourse/discourse/pull/18691
> DEV: Fix test for core change

- app/controllers/encrypt_controller.rb
- assets/javascripts/discourse/initializers/add-search-results.js
- lib/encrypted_search.rb
- spec/requests/encrypt_controller_spec.rb
- test/javascripts/acceptance/encrypt-test.js
Previously, we didn't support these while searching the encrypted PMs.
> FEATURE: add support for before, after & mention filters in seach.

- assets/javascripts/discourse/initializers/decrypt-posts.js
- spec/system/decrypt_encrypted_topic_posts_spec.rb
c.f. https://github.com/discourse/discourse/pull/22820
> DEV: Remove enable_experimental_hashtag_autocomplete logic

- assets/javascripts/discourse/initializers/auto-enable-encrypt.js
- assets/javascripts/discourse/initializers/encrypt-composer.js
- assets/javascripts/discourse/initializers/encrypt-delete-topic.js
- assets/javascripts/discourse/initializers/encrypt-drafts.js
- assets/javascripts/discourse/initializers/encrypt-posts.js
- assets/javascripts/discourse/initializers/fetch-encrypt-keys.js
- assets/javascripts/discourse/initializers/invite-to-encrypted-topic.js
tl;dr: don't use initializer's `container` (or objects looked up in it) in `modifyClass`. Use `getOwner(this)` instead.
> FIX: Use the correct container

- assets/javascripts/discourse/widgets/encrypted-post-timer-counter.js
- assets/javascripts/lib/utils.js
- test/javascripts/acceptance/encrypt-test.js
- test/javascripts/lib/base64-test.js
- test/javascripts/lib/database-safari-test.js
- test/javascripts/lib/database-test.js
- test/javascripts/lib/protocol-test.js
- test/javascripts/lib/protocol-v0-test.js
- test/javascripts/lib/protocol-v1-test.js
- test/javascripts/lib/uploads-test.js
…and newer assertions. (+fix typos)
> DEV: Use qunit-dom, pretender's `response` helper

- test/javascripts/acceptance/encrypt-test.js
Tied to https://github.com/discourse/discourse/pull/25092
> DEV: Update tests for glimmer search menu

- test/javascripts/acceptance/encrypt-test.js
Context: https://github.com/discourse/discourse/pull/25504
> DEV: Update tests for search - soft loaded topic results

- app/services/problem_check/unsafe_csp.rb
- config/locales/server.en.yml
- plugin.rb
- spec/services/problem_check/unsafe_csp_spec.rb
We're promoting problem checks to first class citizens in core. This migrates the problem check to the new API.
> DEV: Promote unsafe CSP check to ProblemCheck

- .discourse-compatibility
- lib/email_sender_extensions.rb
- plugin.rb
Added in https://github.com/discourse/discourse/commit/54a59be6176d2ce02a7aaae8c6b7cb57b1f4bfff
> FIX: use new 'should_add_email_attachments' plugin modifier

- assets/javascripts/lib/database.js
- assets/javascripts/lib/protocol.js
- test/javascripts/acceptance/encrypt-test.js
In accordance with 2020 [RFC591](https://github.com/emberjs/rfcs/blob/master/text/0581-new-test-waiters.md)
See https://github.com/discourse/discourse/pull/29055
> DEV: Use the "new" test waiters

- assets/javascripts/discourse/initializers/encrypt-composer.js
Followup to 875865ded4ee7722d090151501b8db4b804e8c1c
> FIX: Do not warn about replies when allow_new_encrypted_pms=false

- app/controllers/encrypt_controller.rb
- assets/javascripts/discourse/components/encrypt-preferences-dropdown.js
- assets/javascripts/discourse/components/modal/decrypt-all.gjs
- assets/javascripts/discourse/connectors/topic-title/decrypt-topic-button.gjs
- assets/javascripts/discourse/connectors/user-preferences-security/encrypt.js
- assets/javascripts/lib/permanent-topic-decrypter.js
- config/locales/client.en.yml
- plugin.rb
- spec/system/permanent_decrypt_spec.rb
This is accessible from the Encrypt dropdown menu in the user preferences security tab. When run, it will loop through all Encrypted PMs which the user can access and attempt to decrypt them permanently.
> FEATURE: Add 'decrypt all PMs' functionality

- assets/javascripts/lib/permanent-topic-decrypter.js
The `downloadEncryptedFile` strategy relies on the Content-Disposition header to determine the original filename. That doesn't work on forums with S3 uploads, because cross-origin header access is restricted. This commit switches to looking up the filename from the database instead, so it's always guaranteed to be present. Also bails out if the filename has no extension.
> FIX: Use database for original upload filenames when decrypting
