discourse/discourse-encrypt

assets/javascripts/discourse/initializers/hook-draft.js.es6

It was crashing with discourse-spoiler-alert plugin tests if tests were running after encrypt tests.

TEMP FIX: prevents actions on destroyed container if save happens late

---

assets/javascripts/discourse/initializers/hook-encrypt-upload.js.es6
assets/javascripts/lib/uploadHandler.js.es6
test/javascripts/lib/uploadHandler-test.js.es6

Replace isAnImage with isImage from core to fix upload errors on encrypted messages.
* Also split functions from hook-encrypt-upload to new
file for easier testing and to catch any future regressions
* Add qunit test

FIX: Replace isAnImage with isImage from core

---

assets/javascripts/discourse/initializers/hook-composer.js.es6
test/javascripts/acceptance/encrypt-test.js.es6

When public/private keys are generated, the private message should be secured by default.
Also, I found a bug. I needed to rename `targetUsername` to `targetRecipients` due to that commit https://github.com/discourse/discourse/commit/eef21625c6b9dd589573bc1771c7075a12e0abc9
Now, when a user without generated keys are added to PM, the secure message becomes unsecured

FIX: When encrypt is enabled, secure message by default

---

assets/javascripts/discourse/initializers/hook-decrypt-topic.js.es6

Joffrey refactored private message title and he introduced private message wrapper
https://github.com/discourse/discourse/commit/6abc2f5072fef6d8088698b60c7d65fba5e36857#diff-9d0c62b053b74993e2b60802a4bfc2e3R2
He also changed the plugin to use that wrapper when we replace the icon
https://github.com/discourse/discourse-encrypt/commit/03274fb54f6cf5cbc1d6be1a88f7582f09975e60
So currently, we are replacing original icon + adding new one which is creating double security
After the fix, it looks like this

FIX: dont display double agent

---

assets/javascripts/discourse/connectors/composer-action-after/encrypt.js.es6
assets/javascripts/discourse/initializers/hook-composer.js.es6

The bug was introduced in that commit (message encrypted by default)- https://github.com/discourse/discourse-encrypt/commit/029ef4a63ff1a2b937671b89e0f7b80b00e145f9
Problem was that the user could not overwrite default encryption. So the message was always encrypted when encryption was enabled. We need to allow the user to overwrite that behaviour.

FIX: default encryption could be overwritten

---

assets/javascripts/discourse/controllers/activate-encrypt.js.es6

A little bit more smooth experience when decrypting
before:
after:

FIX: display decrypting message during decrypt process

---

lib/email_sender_extensions.rb
plugin.rb
spec/lib/email_sender_spec.rb

We should skip sending encrypted attachments as they are pointless and
cannot be decrypted anyway. If a user wants to see them, they need to
decrypt them in Discourse itself.

FIX: do not add encrypted attachments to emails

---

assets/javascripts/discourse/initializers/hook-decrypt-topic.js.es6

When a user is searching for personal messages, if they are encrypted, topic should be decrypted to show something useful.
Also, this is a little bit of an edge case, so to simplify, the excerpt below the title is hidden
Related discourse PR (include data-topic-id in search) - https://github.com/discourse/discourse/pull/9435

FIX: decrypt encrypted title in the search

---

app/mailers/user_notifications_extensions.rb
plugin.rb
spec/lib/email_sender_spec.rb

When we send email notifications about the encrypted private message - instruction that user can respond via email should be removed.
In addition, the message should be sent from no-reply email address.

FIX: information about reply via email is removed

---

assets/javascripts/discourse/initializers/hook-decrypt-post.js.es6

For classic posts, when we generate cooked version we wrap images with lightbox classes
https://github.com/discourse/discourse/blob/master/lib/cooked_post_processor.rb#L416
However, for encrypted message we don't have cooked version so we need to wrap images after successful decryption.

FIX: decorate decrypted images with lightbox

---

app/controllers/encrypt_controller.rb
plugin.rb
spec/requests/encrypt_controller_spec.rb

The bug mentioned here: https://meta.discourse.org/t/min-trust-to-edit-post-setting-interfering-with-discourse-encrypt/163245
Using the guardian was the best and safest approach. 
However, there is a situation when the user cannot edit posts. For example when `min_trust_to_edit_post` is set higher than the user trust level. 
Therefore we can simply check if the user is author of the post.

FIX: encrypt works for a user who cannot edit posts

---

assets/javascripts/discourse/initializers/hook-gather-keys.js.es6

Topic.create() used to throw a TypeError because it expected
arguments[0] to exist and be an Object.

FIX: Check if arguments are valid

---

app/mailers/user_notifications_extensions.rb
spec/lib/email_sender_spec.rb

Topic ID will make the subject of email encrypted message unique (for example `[Discourse] [PM] A secret message #24222`).
This is necessary to prevent incorrect grouping of those emails by some email providers.

FIX: email about encrypted message contains the topic id

---

app/jobs/scheduled/encrypted_post_timer_evaluator.rb
spec/jobs/encrypted_post_timer_evaluator_spec.rb

Fix for error  - NoMethodError (undefined method `persisted?' for nil:NilClass)

FIX: do not error timer when post is already deleted

---

assets/javascripts/discourse/initializers/hook-decrypt-post.js.es6
assets/javascripts/lib/discourse.js.es6

getDebouncedUserIdentities used to resolve only the first returned
promise. It has been renamed to getDebouncedUserIdentity to simplify
the API and the logic behind it.
The green signature checkmark displayed in the UI is displayed only
after the verification process finishes. This did not happen because
the whole process was stuck waiting for the the promise returned by
getDebouncedUserIdentities to be resolved.

FIX: Make sure all user identity promises are eventually resolved

---

assets/stylesheets/common/encrypt.scss

Expand timer div on mobile when the title is too long
Before:
After:

FIX: timer look when long user title

---

app/jobs/scheduled/encrypted_post_timer_evaluator.rb

Order is ignored anyway with combination with `find_each`. It is throwing warnings

FIX: remove order when find_each in the timer job

---

config/locales/client.en.yml
plugin.rb

Annotation that encrypted message will be permanently destroyed was added to e-mail. It is important for the user to know that they have limited time to read the message.
It was mentioned here: https://meta.discourse.org/t/discourse-encrypt-for-private-messages/107918/127

FIX: email annotation that message will be deleted

---

assets/javascripts/discourse/initializers/hook-decrypt-post.js.es6

Both `post-contents` and `post-small-action` widgets should be decrypted.
Basically, I extracted body to decryptPost function and use it in widgets decorators.
Meta: https://meta.discourse.org/t/discourse-encrypt-unable-to-see-close-message/135235

FIX: decrypt small action widget

---

assets/javascripts/discourse/initializers/hook-decrypt-post.js.es6
assets/javascripts/discourse/initializers/hook-decrypt-topic.js.es6
assets/javascripts/lib/debounce.js.es6
assets/javascripts/lib/discourse.js.es6

We recently merged a Discourse core's PR to replace usages of Ember's debounce and discourseDebounce with a new debounce wrapper. The new wrapper works exactly like Ember's debounce but internally calls "run" when called in test mode.
This PR replaces all usages of other debounce functions with the new wrapper and fallbacks to Ember's debounce for backward-compatibility.

DEV: Use the new discourseDebounce function wrapper.

---

assets/javascripts/lib/debounce.js.es6

We need to wrap the new debounce function inside a try block to avoid throwing a "module not found" exception.

FIX: Use Ember's debounce on stable.

---

config/locales/client.en.yml

Group PMs cannot be encrypted. The warning displayed in the composer has caused some confusion with users thinking they can't send group PMs at all. Add "encrypted" to the text to make it clear only encrypted messages can't be sent.
See https://meta.discourse.org/t/discourse-encrypt-for-private-messages/107918/136

FIX: Improve warning for group PMs

---

test/javascripts/acceptance/encrypt-test.js.es6

PR https://github.com/discourse/discourse/pull/11726 changes the composer's recipients selector from {{user-selector}} to the new {{email-group-user-chooser}}, and that change breaks the acceptance tests of this plugin since they expect {{user-selector}}. This PR fixes the tests.
Don't merge this until the core PR mentioned above is merged.

DEV: Fix JS acceptance test

---

lib/upload_validator_extensions.rb
spec/lib/upload_validator_spec.rb

There are two sets of allowed extensions (one for images and one for
all the other files) and images were always checked against the wrong
set, which excludes all image extensions. For this reason, the check
for encrypted images always failed.
Co-authored-by: jbrw <jamie@goatforce5.org>

FIX: Correctly check extension of encrypted images

---

assets/javascripts/lib/discourse.js.es6

The waitForPendingTitles promise is intended to resolve once async
decryption work is done. We still want it to resolve successfully
even if the decryption failed, so that the UI continues to display.

FIX: Allow quick access panels to load even if topic key is invalid

---

config/locales/client.en.yml

This warning makes me as a user feel like I've done something wrong. I've changed the warning to make it less stark. Would be nice to be taken to the Generate Paper Key interface first, without the warning, then if the user skips away from it show them the warning.

made paper key warning less stark

---

plugin.rb
spec/serializers/topic_view_serializer_spec.rb

This commit also makes use of the more appropriate `Topic#is_encrypted?` to
decide if encrypted information should be serialized.

FIX: Do not load timer data for non-encrypted posts

---

assets/javascripts/discourse/initializers/hook-decrypt-post.js.es6

Usually, it is the server that inserts Oneboxes, but because the content is encrypted, the server cannot perform the operation.

FIX: Load Oneboxes in encrypted posts

---

app/controllers/encrypted_post_timers_controller.rb
app/jobs/scheduled/encrypted_post_timer_evaluator.rb
assets/javascripts/discourse/initializers/hook-topic-controller.js.es6
config/locales/client.en.yml
plugin.rb
spec/requests/encrypted_post_timers_controller_spec.rb

Previously we added a future to set a time for permanent deletion for encrypted messages.
This feature allows user to permanently delete post even if the timer was not set. When the user clicks the delete button, we inform that message will be permanently deleted and create a timer for 1 minute. It allows the user to rollback if clicked by mistake.
https://user-images.githubusercontent.com/72780/112558913-ef9d6000-8e23-11eb-9186-b522c7709464.mov

FEATURE: permanently delete a private message

---

app/jobs/scheduled/encrypted_post_timer_evaluator.rb
spec/jobs/encrypted_post_timer_evaluator_spec.rb

Memoize was a bad idea when we have more than one pending timers

FIX: don't use memoize in the loop

---

lib/encrypted_post_creator.rb
spec/lib/encrypted_post_creator_spec.rb

Creating encrypted PMs on the server side generated topic keys only for
the other participants, ignoring the user who created the topic.

FIX: Create topic keys for all users on new PM

---

app/mailers/user_notifications_extensions.rb
lib/user_notification_renderer_extensions.rb
plugin.rb
spec/lib/email_sender_spec.rb

Both "In replay to" and "Previous replies" sections should be removed from email as they don't contain any useful information in encrypted messages.

FIX: private message email without in reply to section

---

assets/javascripts/discourse/connectors/composer-action-after/encrypt.hbs
assets/javascripts/discourse/connectors/composer-action-after/encrypt.js.es6
config/locales/server.en.yml
config/settings.yml
package-lock.json
test/javascripts/acceptance/encrypt-test.js.es6

Some sites might want to enforce that all encrypted pms explode. This PR adds two new site settings for requring that all encrypted pms need to explode and another for specifying the required length of time before the pms are auto deleted.
When this site setting is enabled users will not be able to change or turn off the exploding pms option when creating a new PM.

Require time bomb

---

app/controllers/encrypt_controller.rb
assets/javascripts/discourse/initializers/add-search-results.js
spec/requests/encrypt_controller_spec.rb

Endpoint /encrypt/posts did not work when use_pg_headlines_for_excerpt
was enabled because not all fields used by SearchPostSerializer were
present.

FIX: Populate all fields used for serialization

---

app/controllers/encrypt_controller.rb
assets/javascripts/discourse/initializers/add-search-results.js
test/javascripts/acceptance/encrypt-test.js

At this moment, the search uses only the topic title. In this case, it
does not make sense to fetch all posts in a topic, but just the first
one.

PERF: Fetch only first posts for search cache

---

assets/javascripts/discourse/initializers/add-search-results.js

`results.grouped_search_result.type_filter` is not always defined.

FIX: Do not explode if search result is empty

---

assets/javascripts/discourse/initializers/hook-encrypt-upload.js
assets/javascripts/lib/uploads.js
test/javascripts/lib/uploads-test.js

There is no direct way to share information between the the pre-upload
and post-upload stages of the upload pipeline. To workaround this
limitation, the plugin uses a global map indexed by filename, where it
holds file information.
For certain browsers (Safari) and files (with non-ASCII characters in
filename) this method does not work because the filename read by the
browser and the one returned by the server use a different
representation and keys do not match (eg. "fi%CC%88le" vs "f%C3%AFle").
For these files, the plugin will attempt to find the information it
needs by looking up by file size.

FIX: Fallback to file size to lookup file info

---

assets/javascripts/discourse/initializers/hook-decrypt-topic.js
assets/javascripts/lib/database.js
assets/javascripts/lib/discourse.js

Notification were stuck in the loading phase if the state of the browser
was invalid because the promise was never rejected on failure.

FIX: Reject promise if identity cannot be loaded

---

assets/javascripts/lib/database.js

All operations assume an empty identity will be returned instead of
an error being raised.
Follow up to 54d1f79a9eefa7e3a4e4a5b4b1303abe03ab72ed.

FIX: Return an empty identity if loading fails

---

assets/javascripts/lib/database.js
test/javascripts/acceptance/encrypt-test.js
test/javascripts/lib/database-safari-test.js
test/javascripts/lib/database-test.js

In Safari 14, indexedDB.open hangs if used immediately after page was
loaded. Performing other operations as a warm up works around this bug.

FIX: Add workaround for Safari's IndexedDb bug

---

app/controllers/encrypt_controller.rb
lib/encrypted_search.rb
plugin.rb
spec/requests/encrypt_controller_spec.rb

Implementation of search in encrypted posts uses a client sided cache
that contains all possible search results. This data is fetched from
/encrypt/posts and it must contain all associations needed for
displaying the search results.
The old solution did not account for any customizations, such as
plugins that can preload specific information for each search result.

FIX: Preload all associations used for search

---

assets/javascripts/discourse/initializers/hook-decrypt-topic.js
test/javascripts/acceptance/encrypt-test.js
test/javascripts/lib/base64-test.js
test/javascripts/lib/discourse-test.js
test/javascripts/lib/protocol-test.js
test/javascripts/lib/protocol_v0-test.js
test/javascripts/lib/protocol_v1-test.js
test/javascripts/lib/uploads-test.js

The window name used to show the placeholder instead of the decrypted
topic title.

FIX: Show decrypted topic title in window name

---

assets/javascripts/discourse/initializers/decrypt-topics.js

There is a list of CSS selectors that match most of the elements that
contain topic titles. The generic ones can overlap with the more
specific ones. It is best to decrypt the elements matched by generic
ones first and then let the specific ones override them.
This commit fixes the bug that shows two secret icons in header.

FIX: Decrypt titles from generic elements first

---

assets/javascripts/discourse/controllers/activate-encrypt.js
assets/javascripts/discourse/initializers/decrypt-posts.js
assets/javascripts/lib/database.js
assets/javascripts/lib/discourse.js
assets/stylesheets/common/encrypt.scss
test/javascripts/acceptance/encrypt-test.js
test/javascripts/lib/database-safari-test.js
test/javascripts/lib/database-test.js

A user's identity was missing if they had encryption enabled, but the
current device was not activated. To make it easy to use, the user was
prompted to activate the device when they navigated to an encrypted
topic. This behavior changed when `getIdentity` started to return a
rejected promise when user has no identity (it used to return an empty
identity).

FIX: Show activation modal if identity is missing

---

assets/javascripts/discourse/initializers/fetch-encrypt-keys.js

When searching for encrypted PMs, there is a small chance the result
is already part of the result set (for example, when searching for words
from the placeholder). In this case, the result is duplicated.

FIX: Do not add result if already present

---

lib/encrypted_search.rb

It is not technically required, but the serializer needs it to generate
the blurb.

FIX: Ensure post_search_data is present

---

assets/javascripts/discourse/initializers/decrypt-posts.js

The click handler that downloads and decrypts the file was registered
every time the post was processed and that can happen multiple times.

FIX: Do not download and decrypt same file twice

---

lib/encrypted_search.rb
spec/requests/encrypt_controller_spec.rb

It used to include all PMs that user has access to, even if they did not
have a key for the topic.

FIX: Include only PMs that can be read in search

---

plugin.rb

The can_encrypt? method returned true for unauthenticated users if
encrypt_groups was blank. Otherwise, it was raising an error because groups method
was
undefined.

FIX: Anonymous users cannot encrypt PMs

---

assets/javascripts/discourse/initializers/encrypt-uploads.js
assets/javascripts/lib/uppy-upload-encrypt-plugin.js

See https://github.com/discourse/discourse/pull/14222
Now that we are using Uppy in core, we need a new way to preprocess
files for uploads. This is done with an uppy plugin by convention. This
commit introduces the plugin and uses it along with the new
addComposerUploadPreProcessor API _only_ if enable_experimental_composer_uploader
is true for the site.
Do not merge without the core PR merged first.
To test locally, you just have to set `enable_experimental_composer_uploader` to
true, and probably setting `enable_upload_debug_mode` to true is a good idea as
well.
Also note I changed the code to use async/await because it makes it easier to reason
about, and we encrypt the uploads serially as we did with the current non-uppy uploader in core.

DEV: Use new core addComposerUploadPreProcessor API

---

test/javascripts/acceptance/encrypt-test.js

The draft.json API endpoint will be moved to drafts.json. The plugin
does not directly use the API endpoint, but the tests track it to ensure
no plaintext is leaked.

DEV: Test for both draft.json and drafts.json

---

assets/javascripts/discourse/initializers/encrypt-uploads.js

This needs to be done becaus modifyClass calls are not allowed
after lookup was called.

DEV: Move composer controller lookup inside _useStableUploadProcessor

---

assets/javascripts/discourse/initializers/add-search-results.js
lib/encrypted_search.rb

All found posts are added to the search result set, ignoring the limit
of `Search.per_filter` limit and ordered by the date post was created,
in descending order.

FIX: Improve search in encrypted posts

---

assets/javascripts/lib/uppy-upload-encrypt-plugin.js

We should not even attempt to encrypt huge files, we need
to just raise an error and stop further processing of the
file.
Related core PR (do not merge this PR without it):
https://github.com/discourse/discourse/pull/14383

FIX: Raise error on huge file uploads

---

assets/javascripts/discourse/initializers/fetch-encrypt-keys.js

This PR aim to support changes that'll be made by [FIX: empty state message on the user bookmarks page](https://github.com/discourse/discourse/pull/14257). That PR moves the method for loading bookmarks from the model to the route. There is a failed test in that PR that shows that it breaks the discourse-encrypt plugin.
The changes supported in backward compatible manner:
- we can merge this PR firstly
- then we can merge [FIX: empty state message on the user bookmarks page](https://github.com/discourse/discourse/pull/14257) in core
- after that, we can remove code that modifies the bookmark model from Discourse Encrypt

DEV: support changes in user bookmarks in core

---

assets/javascripts/discourse/initializers/encrypt-status.js

After we merge https://github.com/discourse/discourse/pull/14440, the global notice won't treat text as HTML Safe.

DEV: Use HtmlSafe for backup warning.

---

config/locales/server.en.yml
config/settings.yml
lib/site_settings_type_supervisor_extensions.rb
lib/validators/encrypt_enabled_validator.rb
plugin.rb
spec/plugin_spec.rb

This plugin adds validation encrypt_enabled and CSP site settings to
make it impossible to enable unsafe CSP settings and the plugin.
Unsafe CSP is a security risk for the plugin because it makes it easier
for potential attackers to inject malicious code that can steal keys or
encrypted conversations.

FEATURE: Disallow unsafe CSP if plugin is enabled

---

lib/encrypted_post_creator.rb
spec/lib/encrypted_post_creator_spec.rb

In 1492adbc76d we ensured we created a topic key for all the participants
in the PM. However, since the bots (like the system user) have no way to
generate an encryption key, they can't send encrypted messages anymore.
This bypass the check for bots as we don't really care if they can read
the encrypted message. This allow to programmatically send encrypted message
as the system user for example.

FIX: ensure bots can always send encrypted messages

---

test/javascripts/acceptance/encrypt-test.js

We don't consume this field on the client, starting from https://github.com/discourse/discourse/pull/14311. The server will stop returning it in response, starting from https://github.com/discourse/discourse/pull/15220.

DEV: remove unused field from an acceptance test

---

assets/javascripts/discourse/initializers/decrypt-topics.js
assets/stylesheets/common/encrypt.scss
test/javascripts/acceptance/encrypt-test.js

Moving encrypted posts button should be disabled as this feature is not yet supported.

FIX: remove move to button for encrypted messages

---

assets/javascripts/lib/uppy-upload-encrypt-plugin.js

The "name" field is present in both the state and metadata of the files,
but was updated only in the state file. This was an issue because the
server thought it was a regular image and tried to process and failed
because it was in fact an encrypted file.

FIX: Ensure encrypted file name is updated

---

spec/plugin_spec.rb

```
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. `NoMethodError`, `NameError` and `ArgumentError`), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`.
```

DEV: Fix an RSpec warning

---

assets/javascripts/discourse/initializers/decrypt-topics.js

The ember router doesn't guarantee a `currentRouteName` will be available at all times. This was causing failures in some other plugin's tests when discourse-encrypt was loaded at the same time

FIX: Do not error when there is no `currentRouteName`

---

assets/javascripts/discourse/initializers/decrypt-posts.js

```
Deprecation notice: linkSeenHashtags now expects a DOM node as first parameter (deprecated since Discourse 2.8.0.beta7)
```

DEV: Fix `linkSeenHashtags` args deprecation

---

assets/javascripts/discourse/initializers/decrypt-posts.js
config/locales/client.en.yml

It tried to check if the signature is valid by simply comparing the
decrypted "signature" field of the signed message instead of just
verifying it.

FIX: Check signature using crypto primitives

---

assets/stylesheets/common/encrypt.scss

At this moment, it is impossible to convert a private encrypted topic
into a regular or public one. The other impossible action is moving
posts from encrypted topics. This commit ensures both buttons are hidden
(the "move posts" button was already hidden).

FIX: Hide convert to public topic button

---

assets/javascripts/discourse/initializers/add-search-results.js
test/javascripts/acceptance/encrypt-test.js

This commit fixes multiple similar bugs in the search cache management
code where it tried to access object that did not exist, such as keys or
encrypted titles of topics that were not encrypted, maps of encrypted
topics (it does not exist for users with no encrypted topics), etc.

FIX: Check cached objects exist before accessing

---

assets/javascripts/discourse/initializers/decrypt-topics.js
assets/stylesheets/common/encrypt.scss
test/javascripts/acceptance/encrypt-test.js

This functionality has not been implemented yet and using it can result
in broken topic titles.

FIX: Hide quick-edit button for encrypted topics

---

assets/javascripts/discourse/initializers/encrypt-drafts.js

Draft is an Ember Object and this is why 'set' and 'setProperties' must
be used to update the value of its properties.

FIX: Use object methods to set properties of Draft

---

plugin.rb
test/javascripts/acceptance/encrypt-test.js

This removes the use_polymorphic_bookmarks site setting
guard and promotes that code to the only code used.

FEATURE: Promote polymorphic bookmarks

---

lib/topics_controller_extensions.rb
spec/requests/topics_controller_spec.rb

When deleted topic is updated, 403 invalid access status should be returned instead of 500.

FIX: update deleted topic

---

assets/javascripts/discourse/initializers/decrypt-topics.js
assets/stylesheets/common/encrypt.scss
test/javascripts/acceptance/encrypt-test.js

This feature allows users to edit title and tags in the topic page's quick edit method.

FEATURE: allow tagging & quick edit in encrypted PMs.

---

plugin.rb

Not all posts created by a user will automatically invite that user to the
topic (create a topic allowed user). For example, if a user creates a whisper
or small action post. This is a tiny improvement, but necessary to merge
discourse/discourse#18075.

DEV: Delete topic allowed user record in one query

---

spec/lib/encrypted_post_creator_spec.rb

See https://github.com/discourse/discourse/pull/18437, we are removing any references to enable_personal_messages in core and using only personal_message_enabled_groups, which requires auto groups to be assigned in certain specs for them to keep working.

DEV: Fix specs for personal_message_enabled_groups setting

---

test/javascripts/acceptance/encrypt-test.js

In preparation for core PR https://github.com/discourse/discourse/pull/18413 which changes JS to load default yml site settings, the main one needing changes is that now the
allow_uncategorized_topics setting is false
by default, which requires setting the category
in the composer before using it.

DEV: Fix JS tests to use default site settings

---

assets/javascripts/discourse/connectors/user-preferences-security/encrypt.hbs
assets/javascripts/discourse/connectors/user-preferences-security/encrypt.js
assets/javascripts/discourse/initializers/encrypt-composer.js
assets/javascripts/discourse/initializers/encrypt-user-options.js
config/locales/client.en.yml
config/settings.yml
db/migrate/20221102045508_add_encrypt_pms_default_to_user_options.rb
plugin.rb
spec/models/user_spec.rb
test/javascripts/acceptance/encrypt-test.js

Previously, we only had site setting to control default encryption status of PMs. Now users can modify the setting in the user preferences page.

FEATURE: new user option to configure if PMs are default encrypted.

---

db/post_migrate/20221123235603_allow_encrypt_pms_default_to_be_null.rb
plugin.rb
spec/serializers/current_user_serialier_spec.rb

We should allow `encrypt_pms_default` to be null in case plugin is disabled or deleted.
In addition, fallback is added to use value from SiteSetting.

FIX: allow encrypt_pms_default to be null

---

assets/javascripts/discourse/initializers/add-search-results.js
test/javascripts/acceptance/encrypt-test.js

We should include encrypted posts only while searching the personal messages without using a group filter.

UX: don't include encrypted posts while searching group messages.

---

test/javascripts/acceptance/encrypt-test.js

```
Error: QUnit Test Failure: Browser Id 2 - Acceptance: Encrypt - active: searching in group messages
not ok 362 Chrome 108.0 - [2870 ms] - Browser Id 2 - Acceptance: Encrypt - active: searching in group messages
---
actual: >
1
expected: >
2
stack: >
at Assert.strictEqual (http://localhost:7357/assets/chunk.vendors-node_modules_pretender_dist_pretender_es_js-node_modules_qunit_qunit_qunit_js-node_mo-a05e2f.ab90efc90902185d6ad5.js:3595:839)
at Object.<anonymous> (http://localhost:7357/assets/plugins/test/discourse-encrypt_tests.js:1051:14)
negative:
```

DEV: Skip flaky QUnit test

---

assets/javascripts/discourse/initializers/decrypt-posts.js
assets/javascripts/discourse/widgets/encrypted-post-timer-counter.js

This means we don't do extra work on regular posts and also fixes a broken display Organisms/Post in the styleguide when the encrypt plugin is present.
The PR also fixes a typo in the function name for `formatedClock`.

DEV: Only add timer counter on PMs

---

assets/javascripts/discourse/initializers/decrypt-posts.js
spec/plugin_helper.rb
spec/system/decrypt_encrypted_topic_posts_spec.rb

Since the core commit https://github.com/discourse/discourse/commit/93859037ef776b83b9840e528a739050c600922c lookups
for mentions in encrypted posts has been broken. This commit fixes
the issue, using the new fetchUnseenMentions method signature and
adding a system spec to cover this case.

FIX: Broken mention lookup

---

assets/javascripts/discourse/templates/modal/export-key-pair.hbs
config/locales/client.en.yml

Reusing a translation from core within a plugin is a bad idea and `admin.*` strings are only visible to admins.

FIX: "Copy to clipboard" string was only visible to admins

---

assets/javascripts/discourse/initializers/add-search-results.js

You can't set a session key with a dot in string. So we need to replace it with hyphen to fix the issue.

FIX: replace dots `.` in session key to hyphen `-`.

---

test/javascripts/acceptance/encrypt-test.js

The new horizontal user profile navigation has been rolled out as the
default in Discourse core. As such, the `nav-security` class is not
longer valid leading to test failures.

DEV: Update tests after changes to core

---

assets/javascripts/discourse/connectors/user-preferences-security/encrypt.hbs
assets/javascripts/discourse/connectors/user-preferences-security/encrypt.js

To resolve
```
DEPRECATION: The <discourse@component:plugin-connector::ember19469>#save computed property was just overridden. This removes the computed property and replaces it with a plain value, and has been deprecated
```
we need to not use the saved namespace of `save` as it was overriding a already defined computed function printing the deprecation above. Instead use a more unique `savePreference` action name.

DEV: Resolve `save` `computed-property.override` deprecation

---

assets/javascripts/discourse/initializers/decrypt-topics.js

Resolve https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-reopen deprecation being thrown for overriding `Component`

DEV: Resolve `reopen` deprecation

---

assets/javascripts/discourse/initializers/decrypt-topics.js

The legacy user menu has been dropped in core, so these `reopenWidget` calls are just triggering console warnings.

DEV: Remove support for legacy user menu

---

assets/javascripts/discourse/components/modal/rotate-key-pair.js
assets/javascripts/lib/protocol.js

Users who are currently stuck with v0 identities are unable to rotate their identities into v1 because of a bug where the old identity is assumed to be v1 and has signing keys, but v0 identities don't have signing keys. When rotating an identity, the signing keys of the old identity are copied to the new identity to keep old signatures working. However, when the old identity is v0 (which has no signing keys), we attempt to copy the old signature keys (`undefined`) to the new v1 identity, but it ends up with no signing keys and fails to be saved because v1 identities are expected to have signing keys.
This PR fixes the issue by checking for the existence of old signing keys before copying them to the new identity. If there are no signing keys in the old identity, we let the new identity …

FIX: Don't error when rotating identities of protocol-v0

---

assets/javascripts/discourse/connectors/composer-action-after/encrypt.hbs

Why this change? 
`this.model.deleteAfterMinutesLabel` can be set to `null` and when it is `null`, we were rendering a span with a broken translation and no text. This was caught after we started raising an error when a `I18n.translate` is used but is missing an interpolation argument: https://github.com/discourse/discourse/pull/23527

DEV: Avoid rendering label when there is nothing to render

---

assets/javascripts/discourse/initializers/decrypt-posts.js

`cooked` was an Ember SafeString. The internal storage of the string changed from `.string` to `.__string` at some point between Ember 3.28 and Ember 5. Instead, we can use `toString()` which is guaranteed to work in all situations

FIX: Decrypt posts correctly under Ember 5.x

---

assets/javascripts/discourse/initializers/decrypt-posts.js

Modules under pretty-text/engines are asynchronously loaded. Importing them directly from a plugin is risky because there's no guarantee they'll actually be available at the time of import.
In this case, we were only importing a simple string constant, and there's very little risk of it changing. Much safer to just hard-code it.
This change was motivated by https://github.com/discourse/discourse/pull/23859, which significantly refactors the asynchronously-loaded code into more modern patterns.

DEV: Stop importing from `pretty-text/engines`

---

test/javascripts/acceptance/encrypt-test.js

The content is signed with the name 'eviltrout', so let's update the fixture to match

DEV: Avoid signature mismatch error in tests

---

spec/requests/encrypt_controller_spec.rb

In https://github.com/discourse/discourse/pull/24840, `min_trust_to_edit_posts` site setting was replaced by `edit_post_allowed_groups`. This PR replaces the former, deprecated one, with the latter.

DEV: Replace deprecated min_trust_to_edit_post

---

spec/plugin_helper.rb

See https://github.com/discourse/discourse/commit/68a3f7783e76064feb19cf86de53f3f4367e80d1

DEV: Remove the use of `Capybara::Session#quit`

---

plugin.rb

In https://github.com/discourse/discourse/pull/26413 we are changing problem checks to require explicit registration. As part of that we're adding a filtered register to the plugin registry. This PR makes use of that new register.

DEV: Explicitly register problem check

---

assets/javascripts/discourse/connectors/composer-action-after/encrypt.hbs

This was causing a warning on every build
> unexpectedly found "! ~" when slicing source, but expected " "
Not 100% sure of the root cause... but we can stop the noise by removing the `~` from the comments

DEV: Remove `{{~! ~}}` whitespace workaround

---

assets/stylesheets/common/encrypt.scss

This is a companion to https://github.com/discourse/discourse/pull/26752 and shows a 🚫 cursor when hovering over a checklist item in an encrypted post to (hopefully) better signal to the user that checking an item won't work in an encrypted post.

UX: show a 🚫 on checklist items

---

plugin.rb

This check was introduced as a loose guard against admin-initiated-xss attacks on discourse-encrypt. The unsafe-eval directive isn't related to those kind of xss protections. Ultimately: if someone can control a trusted JS script, then they are trusted. unsafe-eval doesn't affect that.

FIX: Remove unsafe-eval from `safe_csp_src?` check

---

assets/javascripts/discourse/initializers/decrypt-posts.js

fetchUnseenHashtagsInContext and linkSeenHashtagsInContext
are now in discourse/app/lib/hashtag-decorator since
https://github.com/discourse/discourse/commit/c7860173c1683fcbe33600d29b5294c0bb228253

DEV: Update hashtags import path

---

lib/email_sender_extensions.rb

It has been changed in 96a0781bc181fdc4bda856bfb90b03ce55e342cf to support adding attachments from more than one post.
Internal ref - t/132149
Context - https://meta.discourse.org/t/e-mail-preview-summary-wrong-number-of-arguments-given-10-expected-1/312888

FIX: add_attachments signature

---

lib/user_extensions.rb

From the `openssl` gem compatibility notes:
```
Deprecate the ability to modify OpenSSL::PKey::PKey instances. OpenSSL 3.0 made EVP_PKEY structure immutable, and hence the following methods are not available when Ruby/OpenSSL is linked against OpenSSL 3.0. [GitHub #480]
OpenSSL::PKey::RSA#set_key, #set_factors, #set_crt_params
OpenSSL::PKey::DSA#set_pqg, #set_key
OpenSSL::PKey::DH#set_pqg, #set_key, #generate_key!
OpenSSL::PKey::EC#private_key=, #public_key=, #group=, #generate_key!
```
Since we can no longer use `OpenSSL::PKey::RSA#set_key`, we have to use
another implementation which I abstracted from https://github.com/net-ssh/net-ssh/pull/875

DEV: Add compatibility with OpenSSL 3

---

assets/javascripts/lib/database.js

IDBOpenDBRequest has one more possible event – `upgradeneeded`.
There's a change it's responsible for the flaky tests.

FIX: Add missing event handler

---

app/controllers/encrypt_controller.rb
assets/javascripts/discourse/components/modal/generate-paper-key.hbs
assets/javascripts/discourse/connectors/topic-title/decrypt-topic-button.gjs
assets/javascripts/lib/permanent-topic-decrypter.js
assets/stylesheets/common/encrypt.scss
config/locales/client.en.yml
config/locales/server.en.yml
config/settings.yml
plugin.rb
spec/system/decrypt_encrypted_topic_posts_spec.rb
spec/system/enable_encryption_spec.rb
spec/system/permanent_decrypt_spec.rb

Introduces a new site setting: 'allow_decrypting_pms'
When enabled, a new button is added below the title of any encrypted PM. This can be used by any participant to decrypt the entire topic (including uploads) permanently, and turn the topic into a regular unencrypted PM.
Also unskips and fixes-up all the system specs. We no longer run encrypt as part of the Discourse core test suite, so the prior concerns about flakiness should be less of an issue.

FEATURE: Allow users to decrypt existing PMs

---

assets/javascripts/lib/permanent-topic-decrypter.js

Filenames are not available to JS in this case, because of CORS concerns. Upload without an original filename.
Followup to 658b87f9c169bba04ec5a701eb90e6365c7e5ecf

FIX: Decryption on sites with external uploads

---

app/controllers/encrypt_controller.rb
spec/system/permanent_decrypt_spec.rb

Followup to 658b87f9c169bba04ec5a701eb90e6365c7e5ecf

FIX: Do not bump topics when decrypting

---

app/controllers/encrypt_controller.rb
spec/system/permanent_decrypt_spec.rb

System user edits will never trigger notifications (see PostRevisor#alert_users). The acting user is still recorded in the edit_reason for auditing purposes.

UX: Avoid triggering notifications when decrypting

---

assets/javascripts/discourse/components/encrypt-enable-dropdown.js
assets/javascripts/discourse/components/encrypt-preferences-dropdown.js
assets/javascripts/discourse/components/modal/manage-paper-keys.hbs
assets/javascripts/discourse/components/modal/reset-key-pair.hbs
assets/javascripts/discourse/components/modal/rotate-key-pair.hbs
assets/javascripts/discourse/connectors/user-preferences-security/encrypt.hbs
assets/javascripts/discourse/initializers/decrypt-posts.js
plugin.rb

This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: Update more deprecated Font Awesome icon names

---

config/locales/server.en.yml
plugin.rb

ProblemChecks are supposed to support custom translation keys, but this isn't supported everywhere. e.g. it's hardcoded here: https://github.com/discourse/discourse/blob/eaa45ae4d0/app/models/admin_notice.rb#L10-L11
Moving encrypt's key to the standard location, so that

FIX: deprecation message
